CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n
# Use the STRIP config specific to the LEDs you're using
CONFIG_WS2812_STRIP=y
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=3

CONFIG_ZMK_POINTING=y

# Enable fetching split peripheral battery levels to the central side
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
# Enable central reporting of split battery levels to hosts
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

CONFIG_LAYOUT_SHIFT_TARGET_JIS=y # 日本語(JIS)レイアウト

CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_HIGH=65
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_LOW=40
CONFIG_RGBLED_WIDGET=y

CONFIG_ZMK_STUDIO=y
